### ISSUE TITLE
 Cannot find module ... rumtime/index.js

### ISSUE THREAD

**Issue by microacup** [einsqing/koahubjs#4]
没有自动编译。

```
> koahubjs-demo@0.0.8 start F:\code\node\koa\koahub-demo
> koahub start app/index.js --watch --compile

'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
module.js:474
    throw err;
    ^

Error: Cannot find module 'F:\code\node\koa\koahub-demo\runtime\index.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by einsqing** [comment]
目前仅支持mac，linux。下一个版本会兼容windows。12.31之前预计发布1.0版本

**Comment by einsqing** [comment]
已修复，支持windows
